spring.application.name=url_shortner

spring.datasource.url=jdbc:postgresql://localhost:5432/tiny
spring.datasource.username=0xhasann
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update