services:
  environment:
    POSTGRES_DB: tiny
    POSTGRES_USER: 0xhasann
    POSTGRES_PASSWORD: password

  ports:
    - "5432:5432"

  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
