input {
    beats {
        port => 5044
    }
}

filter {
    # We'll add log parsing here shortly
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "session-booking-system-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}